### ISSUE TITLE
Nice job, its really working

### ISSUE THREAD

**Issue by tyctor** [oelna/websocket-irc#4]
Hi 

i tried your demo with our irc server and it works, great job
i want to use it in our website for chat functionality
is it possible?

if yes, am i right that only script.js and parser.js is needed?
i will try to create vue component

thanks for answer

**Comment by oelna** [comment]
I have put the project under a MIT licence, so yes, you can use and modify it, as long as the LICENCE.md file stays with the other project files.

In regard to which files are needed: I guess the Javascript files are the most important, but without an interface, like the HTML and CSS that come with them, it won't be much use. You could in theory build your own frontend for the application, but I admit I have not thought too much about things like themes and whether everything still works.

Just try it out, or use the parts that make sense to you :) Best of luck!

**Comment by tyctor** [comment]
thanks for reply

yes, i have to adapt it to work with our web components, but i will try to use as much javascript functionality as will be possible.
we need simpler version with just one channel.
